<?php

/**
 * @file
 * node_validator.module
 */

/**
 * Implements hook_ctools_plugin_type().
 */
function entity_validator_ctools_plugin_type() {
  $plugins['validator'] = array(
    'classes' => array('class'),
  );

  return $plugins;
}

/**
 * Include CTools plugins and get all node validator plugins.
 *
 * @return array
 *   All plugins relate to node validator.
 */
function entity_validator_plugins() {
  ctools_include('plugins');
  return ctools_get_plugins('entity_validator', 'validator');
}

/**
 * Load validator.
 *
 * @param $entity_type
 *  The entity type.
 * @param $bundle
 *  The bundle name.
 *
 * @return AbstractEntityValidate
 */
function entity_validator_load_validator($entity_type, $bundle) {
  $plugins = entity_validator_plugins();

  foreach ($plugins as $plugin) {
    if ($entity_type == $plugin['entity_type'] && $bundle == $plugin['bundle']) {
      $file = $plugin['path'] . '/' . $plugin['class'] . '.php';

      if (file_exists($file)) {
        require_once $file;
      }

      /** @var AbstractEntityValidate $validator */
      $validator = new $plugin['class'];

      return $validator->setBundle($bundle);
    }
  }
}
