<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function node_validator_example_ctools_plugin_directory($module, $plugin) {
  if ($module == 'node_validator') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_menu().
 */
function node_validator_example_menu() {
  $items = array();

  $items['node_validator_example/example'] = array(
    'title' => 'example',
    'page callback' => 'node_validator_example_example',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Page callback;
 */
function node_validator_example_example() {
  node_validator_load_validator('node', 'article')
    ->addField('title', 'foo')
    ->validate();
  return '';
}
